### ISSUE TITLE
Template functionality has changed

### ISSUE THREAD

**Issue by ParadoxPacer** [jonjampen/obsidian-xournalpp#8]
**Describe the bug**
I am a big fan of your plugin. Xournal++ recently had an update that made it so that exported template files end in .xopt. Since your plugin only recognizes templates with the .xopp format, the template funcitonality cannot be used anymore.

Could you update the plugin so that it accepts .xopt as a valid template format?

**Comment by AstyCX** [comment]
Ill take a look at it during this weekend!

**Comment by jonjampen** [comment]
Hi @ParadoxPacer,
Thanks for the feedback!

I am not quite sure where to find the option to create a template with the file ending `.xopt` in Xournal++? Which version of Xournal++ are you using?

Even with the latest nightly release, I can't seem to find that option. When I click on `File > Save As` or `File > Export As` I can only export it to PDF/PNG/SVG/XOJ/XOPP but not XOPT.

Just to clarify: Currently, in my obsidian-xournal++ plugin, the way templates work is that you can create and modify a file in Xournal++ to set it up exactly how you want. Then you save it as an .xopp file and add the link in the plugin settings. So whenever you create a new Xournal++ note from within Obsidian, this template file is copied.

Thanks for sending me more details!

Kind regards
Jon

**Comment by ParadoxPacer** [comment]
Oh I'm sorry,

That's my mistake, i thought the template was created using the "Configure Page Template" Option in Xournal++. I didn't know I had to save a file in the way you described. It works now. Sorry for the inconvenience!

**Comment by jonjampen** [comment]
No worries at all, that's great to hear. I'll have to add a more descriptive text sometime, to make it clearer.

Have a nice evening :)
